import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync,execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
export const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
export const kind=pkg.quant.kind;
const home=()=>process.env.QUANT_PLUGIN_HOME||path.join(os.homedir(),'.local','share','quant-plugins');
const fail=(code,message)=>Object.assign(new Error(message),{code});
const flag=(a,n)=>{const i=a.indexOf('--'+n);return i<0?null:a[i+1]};
const dataRoot=()=>process.env.TUSHARE_ENV_ROOT||path.join(os.homedir(),'tushare-environment');
export const venv=()=>path.join(home(),kind,'venv');
export const python=()=>path.join(venv(),process.platform==='win32'?'Scripts':'bin',process.platform==='win32'?'python.exe':'python');
function run(exe,args,opts={}){const r=spawnSync(exe,args,{encoding:'utf8',...opts});if(r.error)throw fail('EXECUTABLE_UNAVAILABLE',r.error.message);if(r.status!==0)throw fail('COMMAND_FAILED',(r.stderr||r.stdout||'Command failed').slice(-1600));return r.stdout;}
export function hashes(p){const result={};function walk(d,rel=''){for(const e of fs.readdirSync(d,{withFileTypes:true})){if(e.name==='.quant-managed.json')continue;const name=path.join(rel,e.name).split(path.sep).join('/');if(e.isSymbolicLink())throw fail('UNSAFE_SKILL','Symlinks inside Skill are not supported');if(e.isDirectory())walk(path.join(d,e.name),name);else result[name]=crypto.createHash('sha256').update(fs.readFileSync(path.join(d,e.name))).digest('hex');}}walk(p);return result;}
function target(args){const agent=flag(args,'agent');if(!['codex','sealseek'].includes(agent))throw fail('AGENT_REQUIRED','Use --agent codex|sealseek');const t=flag(args,'target');if(t)return path.resolve(t);if(agent==='sealseek')throw fail('TARGET_REQUIRED','Supply the Skill directory advertised by SealSeek with --target');return path.join(process.env.CODEX_HOME||path.join(os.homedir(),'.codex'),'skills',kind);}
export function status(args){const t=target(args);if(!fs.existsSync(t))return {target:t,installed:false,managed:false,current:false};const real=fs.realpathSync(t);let m;try{m=JSON.parse(fs.readFileSync(path.join(real,'.quant-managed.json'),'utf8'));}catch{return {target:t,installed:true,managed:false,current:false};}const actual=hashes(real),canon=hashes(path.join(root,'skills',kind));return {target:t,installed:true,managed:m.package===pkg.name,current:Object.keys(canon).every(k=>k==='agents/openai.yaml'||canon[k]===actual[k]),version:m.version};}
export function install(args){const t=target(args),src=path.join(root,'skills',kind),s=status(args);let backup=null;
 if(s.installed){if(!s.managed&&!args.includes('--adopt'))throw fail('UNMANAGED_TARGET','Use --adopt only after reviewing and authorizing backup/migration');let prior;try{prior=JSON.parse(fs.readFileSync(path.join(t,'.quant-managed.json'),'utf8'));}catch{}if(prior){const actual=hashes(t);const edits=Object.keys(prior.hashes).filter(k=>k!=='agents/openai.yaml'&&actual[k]!==prior.hashes[k]);if(edits.length&&!args.includes('--adopt'))throw fail('LOCAL_EDITS','Local Skill edits detected; review before adopting');}
 backup=t+'.backup-'+crypto.randomUUID();fs.cpSync(fs.realpathSync(t),backup,{recursive:true,errorOnExist:true,force:false});if(fs.lstatSync(t).isSymbolicLink())fs.unlinkSync(t);
 }
 fs.mkdirSync(t,{recursive:true});const canon=hashes(src);for(const rel of Object.keys(canon)){const to=path.join(t,rel);if(rel==='agents/openai.yaml'&&fs.existsSync(to))continue;fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(path.join(src,rel),to);}
 fs.writeFileSync(path.join(t,'.quant-managed.json'),JSON.stringify({package:pkg.name,version:pkg.version,hashes:canon,source:src},null,2));const check=status(args);if(!check.current)throw fail('INSTALL_VERIFY_FAILED','Skill hashes differ');return {...check,backup,source:src};}
export function setup(args){const chosen=flag(args,'python')||process.env.QUANT_PYTHON||'python3';const ver=JSON.parse(run(chosen,['-c','import sys,json;print(json.dumps(list(sys.version_info[:3])))']));if(ver[0]!==3||ver[1]<11)throw fail('PYTHON_VERSION','Python 3.11+ required');if(!fs.existsSync(python())){fs.mkdirSync(path.dirname(venv()),{recursive:true});run(chosen,['-m','venv',venv()]);}run(python(),['-m','pip','install','--disable-pip-version-check',path.join(root,'runtime')]);run(python(),['-c',kind==='tushare'?'import tushare,pandas,pyarrow,qt_research,tushare_env':'import jqcli,click,httpx']);
 if(kind==='tushare'){const d=dataRoot();for(const n of ['config','strategies','reports','data','state'])fs.mkdirSync(path.join(d,n),{recursive:true});const reg=path.join(d,'config','read-api-registry.json');if(!fs.existsSync(reg))fs.copyFileSync(path.join(root,'runtime','resources','read-api-registry.json'),reg);}
 return {runtime:python(),python:ver,version:pkg.version,data_root:kind==='tushare'?dataRoot():null};}
export function doctor(){let runtime={available:false};if(fs.existsSync(python())){try{runtime=JSON.parse(run(python(),['-c',`import json,sys,importlib.metadata as m;print(json.dumps({'available':True,'entry':sys.executable,'version':sys.version.split()[0],'package':m.version('${kind==='tushare'?'tushare-local-environment':'jqcli'}')}))`]));}catch(e){runtime={available:false,code:e.code};}}
 return {healthy:Number(process.versions.node.split('.')[0])>=22&&runtime.available,node:process.version,runtime,package:pkg.name,version:pkg.version,skill_source:path.join(root,'skills',kind),data_root:kind==='tushare'?dataRoot():null,configuration_required:true};}
export function delegate(args){if(!fs.existsSync(python()))throw fail('RUNTIME_NOT_INSTALLED','Run '+(kind==='tushare'?'tushare-env':'jqcli')+' setup first');const env={...process.env,PYTHONUTF8:'1',PYTHONIOENCODING:'utf-8'};if(kind==='tushare')env.TUSHARE_ENV_ROOT=dataRoot();const r=spawnSync(python(),['-c',kind==='tushare'?'from tushare_env.cli import main;raise SystemExit(main())':'from jqcli.cli import main;main()',...args],{stdio:'inherit',env});if(r.error)throw fail('EXECUTABLE_UNAVAILABLE',r.error.message);return r.status??1;}
export function specialStrategy(args){const i=args.indexOf('strategy'),action=args[i+1];if(i<0||!['check','scaffold'].includes(action)||kind!=='jqcli')return null;if(!fs.existsSync(python()))throw fail('RUNTIME_NOT_INSTALLED','Run jqcli setup');if(action==='check'){const f=flag(args,'file');if(!f)throw fail('INPUT_REQUIRED','Use strategy check --file SOURCE');const r=spawnSync(python(),[path.join(root,'skills','jqcli','scripts','check_joinquant_strategy.py'),f],{stdio:'inherit'});return r.status??1;}const name=flag(args,'name');if(!name)throw fail('INPUT_REQUIRED','Use strategy scaffold --name NAME --root DIR');const r=spawnSync(python(),[path.join(root,'skills','jqcli','scripts','scaffold_strategy_workspace.py'),name,'--root',flag(args,'root')||'.'],{stdio:'inherit'});return r.status??1;}
export function update(args){if(args[1]==='check'){const tag=flag(args,'tag')||'latest';if(!['next','latest'].includes(tag))throw fail('INVALID_TAG','Use latest|next');return {current:pkg.version,available:JSON.parse(run(process.platform==='win32'?'npm.cmd':'npm',['view',pkg.name+'@'+tag,'version','--json'])),tag};}const version=flag(args,'version');if(!version||!/^\d+\.\d+\.\d+(?:-[\w.-]+)?$/.test(version))throw fail('VERSION_REQUIRED','Use an exact --version');run(process.platform==='win32'?'npm.cmd':'npm',['install','-g',pkg.name+'@'+version]);const cli=kind==='tushare'?'tushare-env':'jqcli';const observed=JSON.parse(run(cli,['version']));if(observed.result.version!==version)throw fail('UPDATE_VERIFY_FAILED','CLI version mismatch');run(cli,['setup']);let skill=null;if(flag(args,'agent'))skill=JSON.parse(run(cli,['skill','update','--agent',flag(args,'agent'),...(flag(args,'target')?['--target',flag(args,'target')]:[])]));return {version,skill};}
export function main(args=process.argv.slice(2)){try{let result;if(args[0]==='version'||args[0]==='--version')result={package:pkg.name,version:pkg.version};else if(args[0]==='capabilities')result=JSON.parse(fs.readFileSync(path.join(root,'capabilities.json'),'utf8'));else if(args[0]==='doctor')result=doctor();else if(args[0]==='setup')result=setup(args);else if(args[0]==='skill'){if(args[1]==='source')result={source:path.join(root,'skills',kind),version:pkg.version};else if(args[1]==='status')result=status(args);else if(['install','update'].includes(args[1]))result=install(args);else throw fail('COMMAND_UNKNOWN','Use skill source|status|install|update');}else if(args[0]==='update')result=update(args);else{const s=specialStrategy(args);if(s!==null)return s;return delegate(args);}console.log(JSON.stringify({ok:true,result}));return 0;}catch(e){console.log(JSON.stringify({ok:false,error:{code:e.code||'OPERATION_FAILED',message:e.message}}));return 1;}}
